name: blasc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.20
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  google_fonts: ^2.3.1
  firebase_storage: ^10.2.9
  firebase_storage_web: ^3.2.10
  image_picker: ^0.8.4+11
  file_picker: ^4.5.1
  dotted_border: ^2.0.0+2
  uuid: ^3.0.6

# dependency_overrides:
#   firebase_storage_platform_interface: 4.1.1
#   cloud_firestore_platform_interface: 5.5.1
#   firebase_auth_platform_interface: 6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
    
  uses-material-design: true

 
